### CREATE EXPERT
POST http://localhost:6000/expert/add_expert
Content-Type: application/json

{
    "mod_expert_name": "John Doe",
    "mod_expert_mobile": "9876543210",
    "mod_expert_role": "Senior Developer",
    "mod_expert_profile": "https://example.com/profile.jpg"
}

### GET EXPERT
GET http://localhost:6000/expert/read_all_experts

### GET EXPERT by mod_expert_id
GET http://localhost:6000/expert/get_expert/6c6de079-421f-4362-be94-6383f4a8907f

###Update Expert by mod_expert_id
PUT http://localhost:6000/expert/update_expert/f996f10f-e271-4dd8-85e3-ae76a3e16640

{

    "mod_id": ["6503caf1-fb75-4640-99f2-d6a529b71205"]
}
### Update poc_id separately by mod_expert_id 
PUT http://localhost:6000/expert/update_poc/6c6de079-421f-4362-be94-6383f4a8907f
Content-Type: application/json

{
    "poc_id": ["poc123", "poc456"]
}

### Update mod_id separately by mod_expert_id 
PUT http://localhost:6000/expert/update_mod/f996f10f-e271-4dd8-85e3-ae76a3e16640    
Content-Type: application/json

{
    "mod_id": ["6503caf1-fb75-4640-99f2-d6a529b71205"]
}

### Delete an Expert by mod_expert_id
DELETE http://localhost:6000/expert/delete_expert/6c6de079-421f-4362-be94-6383f4a8907f

### GET EXPERT NAME BY MOD_ID
GET http://localhost:6000/expert/get_expert_name/6503caf1-fb75-4640-99f2-d6a529b71205

