### Create MCQ
POST http://localhost:8000/mcq/add_mcq
Content-Type: application/json

{
    "mcq_question": "What is JavaScript?",
    "mcq_options": ["Language", "Library", "Framework", "Database"],
    "mcq_answer": "Language",
    "mcq_tag": ["Programming", "Frontend"]
}

### Get All MCQs
GET http://localhost:8000/mcq/get_all_mcqs

### Get a Single MCQ by ID
GET http://localhost:8000/mcq/get_mcq/1742981934515

### Update MCQ
PUT http://localhost:8000/mcq/update_mcq/
Content-Type: application/json

{
    "mcq_id": "49e38dce-e39f-4a59-9d8c-f44b3ce4985b",
    "mcq_question": "What is JavaScript?",
    "mcq_options": ["Runtime", "Library", "Framework", "Language"],
    "mcq_answer": "Language",
    "mcq_tag": ["Programming", "Frontend"]
}

### Delete MCQ
DELETE http://localhost:8000/mcq/remove_mcq/8ffd4d6b-9de0-4b18-b4bc-3bde05ced2b0

### Submit Result to External Service via Consul
POST http://localhost:8000/mcq/submit_result
Content-Type: application/json

{
  "result_user_id": "",
  "result_test_id": "",
  "result_score": 85,
  "result_poc_id": "",
  "result_id": ""
}
