### Create Module
POST http://localhost:4000/modules_gateway/modules/add_module
Content-Type: application/json

{
  "mod_name": "Full Stack Devcscselopment",
  "mod_tech": "MERcscN",
  "mod_duration": "6 monsccths"
}

### Get All Modules
GET http://localhost:4000/modules_gateway/modules/get_all_module

### Get Module by ID
GET http://localhost:4000/modules_gateway/modules/get_module_by_id/6503caf1-fb75-4640-99f2-d6a529b71205

### Update Module
PUT http://localhost:4000/modules_gateway/modules/update_module/bb38fac7-6a3f-4f31-b670-eec4975888ca
Content-Type: application/json

{
  "mod_name": "Advanced Full Stack",
  "mod_tech": "MERN + React Native",
  "mod_duration": "8 months"
}

###  Delete Module
DELETE http://localhost:4000/modules_gateway/modules/delete_module/bb38fac7-6a3f-4f31-b670-eec4975888ca

### Get Module Name by ID
GET http://localhost:4000/modules_gateway/modules/get_module_name_by_id/6503caf1-fb75-4640-99f2-d6a529b71205
