POST http://localhost:9000/individual/post-individual
Content-Type: application/json

{
 
  "module_id": "863662d6-7565-4ba7-aaa5-5ecc9d6cae9e",
  "module_poc_id": "9ccefe74-f80c-4427-804e-827a61d7619a",
  "user_id": "71dd0f23-9c6d-4f03-ab37-a454f90fdac5",
  "org_id":"2112040a-a6ac-4148-a32b-a358dd5176a0",
  "result_test_id": "b2b727d1-f034-4636-9a28-b6cd84d07043",
  "date":"28/03/2025",
  "result_mcq_score": 42,
  "result_coding_score": 0,
  "total_mark": 50
}
###
###

### POST Individual Test Data
POST http://localhost:9000/individual/post-individual
Content-Type: application/json

{
  "module_name": "Java Basics",
  "user_name": "Visvak Sena",
  "module_id": "mod123",
  "org_id": "org456",
  "college_name": "Mec",
  "module_poc_name": "Dr. Ram Kumar",
  "module_poc_id": "poc789",
  "module_duration": "01/05/2025 - 31/05/2025",
  "user_id": "user001",
  "result_test_id": "test3789",
  "date": "11/05/2025",
  "result_mcq_score": 15,
  "result_coding_score": 25,
  "total_mark": 50,
  "aggregate_score": 50
}


//get data by using report_id 
###
GET http://localhost:9000/individual/get-by-report-id/759e1c10-bb0e-4a18-8926-8d75443c2831



//get user details by using user_id 
###
GET http://localhost:9000/individual/get-user-details-by-user-id/717150b2-2a19-45e8-9c24-69d93b4751c2


### get poc by using poc_id
###
GET http://localhost:9000/individual/get_poc_by_poc_id/9ccefe74-f80c-4427-804e-827a61d7619a

//getting org name by org_id
###
GET http://localhost:9000/individual/get_org_by_org_id/2112040a-a6ac-4148-a32b-a358dd5176a0

###getting mod id from express_mod by using mod_id
GET http://localhost:9000/individual/get-by-mod-id_express_mod/863662d6-7565-4ba7-aaa5-5ecc9d6cae9e
###
GET http://localhost:9000/individual/get-all-individual


###
PUT http://localhost:9000/individual/update-individual
Content-Type: application/json

{
   "_id": "67f75cebb2fa02834f521440",
    "college_name": " Muthayammal Enginnering College",
    "user_name": "Nishanth S",
    "module_name": "Docker & Kubernetes",
    "module_id": "863662d6-7565-4ba7-aaa5-5ecc9d6cae9e",
    "module_poc_name": "Bhuvana",
    "module_poc_id": "9ccefe74-f80c-4427-804e-827a61d7619a",
    "module_duration": "06/04/2025 - 10/04/2025",
    "user_id": "63110a24-e632-4042-87f9-0e8e078f33aa",
   "total_mark": 50
  

  
}
###

// ❌ Delete a test by user_id and result_test_id
###
DELETE http://localhost:9000/individual/delete-test/efe06b56-aaf6-4198-840f-4a2b966b55f0/test_002

###
DELETE http://localhost:9000/individual/delete-user/717150b2-2a19-45e8-9c24-69d93b4751c2