### Create MCQ
POST http://localhost:4000/mcq_gateway/mcq/add_mcq
Content-Type: application/json

[
    {
        "mcq_question": "What is Express.js?",
        "mcq_options": ["Framework", "Library", "Runtime", "Database"],
        "mcq_answer": "Framework",
        "mcq_tag": ["Backend", "Node.js"]
    },
    {
        "mcq_question": "What is React?",
        "mcq_options": ["Framework", "Library", "Language", "Database"],
        "mcq_answer": "Library",
        "mcq_tag": ["Frontend", "JavaScript"]
    }
]

### Get All MCQs
GET http://localhost:4000/mcq_gateway/mcq/get_all_mcqs

### Get All MCQs
GET http://localhost:4000/mcq_gateway/mcq/get_mcq/78b70d32-9839-457d-870c-6c36fe2fad5d


### Update MCQ  
PUT http://localhost:4000/mcq_gateway/mcq/update_mcq
Content-Type: application/json

{
    "mcq_id": "49e38dce-e39f-4a59-9d8c-f44b3ce4985b",
        "mcq_question": "What is React?",
        "mcq_options": ["Framework", "Library", "Language", "Database"],
        "mcq_answer": "Library",
        "mcq_tag": ["Frontend", "JavaScript"]
}

### Delete MCQ
DELETE http://localhost:4000/mcq_gateway/mcq/remove_mcq
Content-Type: application/json

{
"test_mcq_id": "1742980566517"
}


### Submit Result to External Service via Consul
POST http://localhost:4000/mcq_gateway/mcq/submit_result
Content-Type: application/json

{
  "result_user_id": "user_123",
  "result_test_id": "test_456",
  "result_score": 85,
  "result_poc_id": "poc_789",
  "result_id": "result_001"
}
