### Create Test
POST http://localhost:4000/test_gateway/test/create
Content-Type: application/json

{
    "test_name": "Sample Test",
    "test_language": "Css",
    "test_total_score": 100,
    "test_mcq_id": [],
    "test_coding_id": []
}

### Get All Tests
GET http://localhost:4000/test_gateway/test/all

### Get Test by ID
GET http://localhost:4000/test_gateway/test/get_by_test_id/9eb93e29-0857-46e3-8ffd-7fe50249eab6

### Update Test (Add MCQ & Coding Test ID)
PUT http://localhost:4000/test_gateway/test/update
Content-Type: application/json

{
    "test_id": "9eb93e29-0857-46e3-8ffd-7fe50249eab6",
    "mcq_id": ["78b70d32-9839-457d-870c-6c36fe2fad5d","d3d88451-7419-4bcd-ae0c-d04e515b2546","e342d539-0365-4dbc-ae2d-6117518695ed"],
    "coding_test_id": ["coding_id-5","coding_id-6"]
}

### Delete Test
DELETE http://localhost:4000/test_gateway/test/delete
Content-Type: application/json

{
    "test_id": "e2231823-e386-4e63-adf6-52795b74d382"
}

### Remove MCQ from Test Using Test ID & MCQ ID
PUT http://localhost:4000/test_gateway/test/remove_mcq_from_test
Content-Type: application/json

{
    "test_id": "9eb93e29-0857-46e3-8ffd-7fe50249eab6",
    "mcq_id": "d3d88451-7419-4bcd-ae0c-d04e515b2546"
}


