### GET - Fetch All Attendance Records
GET http://localhost:9000/attendance

### GET - Fetch Attendance by mod_id, class_name, poc_id
GET http://localhost:9000/attendance?mod_id=M15&class_name=Class s
### ✅ POST - Create a New Attendance Record
POST http://localhost:9000/attendance
Content-Type: application/json

{
  
  "mod_id": "M15",
  "class_name": "Class s",
  "poc_id": "12345",
  "date": "2025-03-14",
  "present_count": 20,
  "total_students": 35
}



###
PUT http://localhost:9000/attendance/67d4715e75c60d1769b90eff
Content-Type: application/json

{
  "mod_id": "M9",
  "class_name": "Class A",
  "poc_id": "12345",
  "date": "2025-03-14",
  "present_count": 30,
  "total_students": 35
}

###  DELETE - Remove an Attendance Record (Replace {id} with actual record ID)
DELETE http://localhost:9000/attendance/67d4715e75c60d1769b90eff