### Create a new POC
POST http://localhost:4000/poc_gateway/poc/add_poc
Content-Type: application/json

{
    "mod_poc_name": "Selva",
    "mod_poc_role": "AP",
    "mod_poc_email": "selva@gmail.com",
    "mod_poc_mobile": "7894514789"
}

### Get all POCs
GET http://localhost:4000/poc_gateway/poc/read_all_poc

### Get POC by mod_poc_id
GET http://localhost:4000/poc_gateway/poc/get_poc_by_poc_id/9ccefe74-f80c-4427-804e-827a61d7619a

### Update POC details
PUT http://localhost:4000/poc_gateway/poc/update_poc
Content-Type: application/json

{
    "mod_poc_id": "9ccefe74-f80c-4427-804e-827a61d7619a",
    "mod_id":"863662d6-7565-4ba7-aaa5-5ecc9d6cae9e"
}

### Update only mod_tests and mod_users
PUT http://localhost:4000/poc_gateway/poc/update_mod_field
Content-Type: application/json

{
    "mod_poc_id": "9ccefe74-f80c-4427-804e-827a61d7619a",
    "mod_tests": [],
    "mod_users": ["717150b2-2a19-45e8-9c24-69d93b4751c2","528f7cb8-0bfe-4366-a98d-831719ec53e6"]
}

### Update Test ID for a POC
PUT http://localhost:4000/poc_gateway/poc/update_test
Content-Type: application/json

{
    "mod_poc_id": "9ccefe74-f80c-4427-804e-827a61d7619a",
    "test_id": ["b2b727d1-f034-4636-9a28-b6cd84d07043"]
}

### Delete Test by mod_poc_id
DELETE http://localhost:4000/poc_gateway/poc/delete_test/f4e816ef-f669-405c-be8c-eb5338c6ef67

### Delete POC by mod_poc_id
DELETE http://localhost:4000/poc_gateway/poc/delete_poc/f4e816ef-f669-405c-be8c-eb5338c6ef67

###  GET POC BY USER
GET http://localhost:4000/poc_gateway/poc/mod_by_user/1343fa0e-8b57-4b08-be4d-4ab750ec2806

### GET MOD AND POC AND TEST ID BY USER ID 
GET http://localhost:4000/poc_gateway/poc/mod_and_poc/1343fa0e-8b57-4b08-be4d-4ab750ec2806



### GET MOD AND POC AND TEST ID BY USER ID 
GET http://localhost:4000/poc_gateway/poc/get_poc_certificate_by_mod_id/6503caf1-fb75-4640-99f2-d6a529b71205