### Create a new POC
POST http://localhost:6000/poc/add_poc
Content-Type: application/json

{
    "mod_poc_name": "vetri",
    "mod_poc_role": "AP",
    "mod_poc_email": "vetri@gmail.com",
    "mod_poc_mobile": "26283847784"
}

### Get all POCs
GET http://localhost:4000/poc/read_all_poc

### get poc by using mod_id
GET http://localhost:6000/poc/get_poc_by_mod_id/6503caf1-fb75-4640-99f2-d6a529b71205


### Get POC by mod_poc_id
GET http://localhost:6000/poc/get_poc_by_poc_id/3fcfeeae-653a-410c-b54c-4030210b0c15
### Update POC details
PUT http://localhost:6000/poc/update_poc
Content-Type: application/json

{
    "mod_id":"6503caf1-fb75-4640-99f2-d6a529b71205",
    "mod_poc_id": "3fcfeeae-653a-410c-b54c-4030210b0c15"
}

### Update only mod_tests and mod_users
PUT http://localhost:6000/poc/update_mod_field 
Content-Type: application/json

{
    "mod_poc_id": "90fa404e-b09d-42e1-a7c5-1cd0f90b4299",
    "mod_tests": ["57b7bb55-a49e-4065-b38d-fbd13c396d2b","57b7bb55-a49e-4065-b38d-fbd13c396d2b"],
    "mod_users": ["1343fa0e-8b57-4b08-be4d-4ab750ec2806","717150b2-2a19-45e8-9c24-69d93b4751c2"]
}

### ADD TEST BY POC ID

PUT http://localhost:6000/poc/update_test
Content-Type: application/json

{
    "mod_poc_id": "90fa404e-b09d-42e1-a7c5-1cd0f90b4299",
    "test_id": ["9eb93e29-0857-46e3-8ffd-7fe50249eab6"]
}

### Delete Test by mod_poc_id
DELETE http://localhost:6000/poc/delete_test/57b7bb55-a49e-4065-b38d-fbd13c396d2b

### Delete POC by mod_poc_id
DELETE http://localhost:6000/poc/delete_poc/8ddcfe54-c282-4ce1-80d2-21cab5ec7819

###  GET POC BY USER
GET http://localhost:6000/poc/mod_by_user/717150b2-2a19-45e8-9c24-69d93b4751c2


### GET MOD AND POC AND TEST ID BY USER ID 
GET http://localhost:6000/poc/mod_and_poc/717150b2-2a19-45e8-9c24-69d93b4751c2

/// report ///

### get report by using mod_poc_id
GET http://localhost:4000/poc/get_poc_report_by_poc_id/9ccefe74-f80c-4427-804e-827a61d7619a
###

### get poc by using mod_poc_id
GET http://localhost:6000/poc/get_poc/3fcfeeae-653a-410c-b54c-4030210b0c15
###


### get report by using mod_poc_id
GET http://localhost:6000/poc/get-by-mod-id/863662d6-7565-4ba7-aaa5-5ecc9d6cae9e
###

### get report by using mod_poc_id
GET http://localhost:4000/poc/get_expert_using_poc/9ccefe74-f80c-4427-804e-827a61d7619a



### Get full expert details using mod_poc_id
PUT http://localhost:4000/poc/generate_report/9ccefe74-f80c-4427-804e-827a61d7619a
Content-Type: application/json

{
  "title": "asdfghjk",
  "company":"abcd",
  "summary": [
    {
      "day": "Day 1",
      "topicsCovered": "Introduction to Module",
      "technicalTasksPerformed": "Task 1, Task 2",
      "gitLink": "http://example.com/git-repo-1",
      "attendancePresent": ["User 1", "User 2"],
      "attendanceAbsent": ["User 3"]
    },
    {
      "day": "Day 2",
      "topicsCovered": "Advanced Topics in Module",
      "technicalTasksPerformed": "Task 3, Task 4",
      "gitLink": "http://example.com/git-repo-2",
      "attendancePresent": ["User 1", "User 2", "User 4"],
      "attendanceAbsent": []
    },
     {
      "day": "Day 3",
      "topicsCovered": "Advanced Topics in Module",
      "technicalTasksPerformed": "Task 3, Task 4",
      "gitLink": "http://example.com/git-repo-2",
      "attendancePresent": ["User 1", "User 2", "User 4"],
      "attendanceAbsent": []
    }
    
  ]
}

###

GET http://localhost:6000/poc/poc/report/9ccefe74-f80c-4427-804e-827a61d7619a